/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DatosController;
import javax.swing.JInternalFrame;

/**
 *
 * @author Defolt
 */
public class Pantalla extends javax.swing.JFrame {
    private DatosController datosController = new DatosController();
     Eliminar eliminar=new Eliminar(datosController);
     Actualizar actualizar=new Actualizar(datosController);
     Mostrar mostrar=new Mostrar(datosController);
     Crear crear=new Crear(datosController);
    

    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnn = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Hatsune-Miku-Transparent-Background.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel1.setText("Bienvenido al menu!!!");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 12)); // NOI18N
        jLabel2.setText("Seleccione la opcion que desea realizar :)");

        btn1.setText("Crear");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear(evt);
            }
        });

        btn2.setText("Leer");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leer(evt);
            }
        });

        btn4.setText("Eliminar");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar(evt);
            }
        });

        btn3.setText("Actualizar");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Hatsune-Miku-Transparent-Background.png"))); // NOI18N

        btnn.setBackground(new java.awt.Color(255, 0, 0));
        btnn.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        btnn.setText("NO TOCAR!");
        btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no0(evt);
            }
        });

        Contenedor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(btn1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(btn2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(btn4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(btn3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(btnn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear
    
    Contenedor.add(crear);
    crear.setVisible(true);
    crear.setLocation((Contenedor.getWidth() - crear.getWidth()) / 2,(Contenedor.getHeight() - crear.getHeight()) / 2);
// TODO add your handling code here:
    }//GEN-LAST:event_Crear

    private void Leer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leer
    
    Contenedor.add(mostrar);
    mostrar.setVisible(true);
    mostrar.setLocation((Contenedor.getWidth() - mostrar.getWidth()) / 2,(Contenedor.getHeight() - mostrar.getHeight()) / 2);
    // TODO add your handling code here:
    }//GEN-LAST:event_Leer

    private void Actualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar
    
    Contenedor.add(actualizar);
    actualizar.setVisible(true);
    actualizar.setLocation((Contenedor.getWidth() - actualizar.getWidth()) / 2,(Contenedor.getHeight() - actualizar.getHeight()) / 2);
    }//GEN-LAST:event_Actualizar

    private void Eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar
   
    Contenedor.add(eliminar);
    eliminar.setVisible(true);
    eliminar.setLocation((Contenedor.getWidth() - eliminar.getWidth()) / 2,(Contenedor.getHeight() - eliminar.getHeight()) / 2);

    // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar

    private void no0(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no0
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_no0

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Contenedor;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
